### ISSUE TITLE
Create prisma schema & migration

### ISSUE THREAD

**Issue by Gabryjiel** [hyter99/AI_22-23_L1#10]
Edit /prisma/schema.prisma with content from #9.

[Schema](https://www.prisma.io/docs/concepts/components/prisma-schema)

[Migrations](https://www.prisma.io/docs/concepts/components/prisma-migrate)

**Comment by Gabryjiel** [comment]
This command may prove useful to you
```
npx prisma migrate dev --name init
```

Your migration should be the initial one. Delete the one that already exists.

**Comment by marcin98b** [comment]
https://github.com/hyter99/AI_22-23_L1/pull/25
