### ISSUE TITLE
[DO] Create docker-compose.yml file

### ISSUE THREAD

**Issue by Gabryjiel** [hyter99/AI_22-23_L1#13]
How many images? Is two enough for now?

- App
- DB (postres prefered)

**Comment by pikrog** [comment]
Three if we have separate front & back-end servers.

**Comment by Gabryjiel** [comment]
Right now, I don't think so.

Backend server can serve static files so it should be good enough.

If frontend will be in need of something more than purely static files, then we can think about third one.
