### ISSUE TITLE
[ALL] Configure eslint & prettier

### ISSUE THREAD

**Issue by Gabryjiel** [hyter99/AI_22-23_L1#14]
Modify eslint & prettier configuration

**Comment by martinZz8** [comment]
In my branch [initial-frontend](https://github.com/hyter99/AI_22-23_L1/tree/initial-frontend) I have added **.prettierignore** file. I also added it to **.gitigore** file.
The case is that I don't think prettier very helpful for me. So I decided to disable it for myself.

**Comment by martinZz8** [comment]
I also added the condition of '**@typescript-eslint/ban-ts-comment': 'off'** in **.eslintrc.js** file. If someone can't get into the idea how to solve the TypeScript problem and it prevents him from further coding, he can temporarily disable it for TypeScript processor. As he did it he can create an issue with it and we can solve it together.

**Comment by Gabryjiel** [comment]
I'm mainly thinking of adding bunch of plugins to eslint.
```
        "plugin:import/recommended",
        "plugin:import/typescript",
        "plugin:react/recommended",
        "plugin:react-hooks/recommended",
        "plugin:jsx-a11y/recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:prettier/recommended"
```
