### ISSUE TITLE
[BE] Prepare specification for API endpoints

### ISSUE THREAD

**Issue by Gabryjiel** [hyter99/AI_22-23_L1#26]
Prepare basic specification for API endpoints:

- url
- method
- query params / body
- response body
- status code
- role access

**Comment by pikrog** [comment]
[PDF](https://github.com/hyter99/AI_22-23_L1/files/9842936/api.pdf)

[Editable](https://github.com/hyter99/AI_22-23_L1/files/9842933/api.docx)

**Comment by pikrog** [comment]
[View PDF](https://github.com/hyter99/AI_22-23_L1/files/9842968/api.pdf)

[Editable DOCX](https://github.com/hyter99/AI_22-23_L1/files/9842970/api.docx)

**Comment by Gabryjiel** [comment]
Add GET for offers.

Throw .pdf file into ./docs/ with PR.

**Comment by pikrog** [comment]
[Updated editable DOCX](https://github.com/hyter99/AI_22-23_L1/files/9853269/api.docx)

Do we need that `transaction_array` field sent by the `/profile/:id/sell-offers` and `/profile/:id/buy-offers` endpoints?

cc @martinZz8 @BartoszGrz

**Comment by martinZz8** [comment]
I think this field is redundant. We can remove it from endpoints.

**Comment by pikrog** [comment]
Agreed. Any other suggestions?

**Comment by Gabryjiel** [comment]
Are we going to do pagination with "page" and "take" attributes or do we prefer only "page"?

Basically, "take" tells how many rows should be fetched for a single page.
