### ISSUE TITLE
[DB] Prepare seeds for database

### ISSUE THREAD

**Issue by Gabryjiel** [hyter99/AI_22-23_L1#30]
Prepare test data for database.

Use [faker-js](https://www.npmjs.com/package/@faker-js/faker) and [prisma](https://www.prisma.io/docs/guides/database/seed-database).

**Comment by Gabryjiel** [comment]
Hey, as you can see there's a bug: 
![obraz](https://user-images.githubusercontent.com/33352685/201329842-0e50776a-f34c-4af2-bc50-ba58c72227d1.png)

Problem stems from the fact that during seeding we don't use sequence in postgres but insert primary keys/ids manually.

Please modify "seed.ts" script to omit primary keys. Example below:

```TS
// BEFORE 
const users: User[] = [];

const user: User = {
      userId: i,
      email: userEmail,
      password: hashedPassword,
      passwordSalt: salt,
      name: userName,
      surname: userSurname,
      balanceCents: userBalanceCents,
    };
```

```TS
// AFTER: No more "userId" in object
const users: Prisma.UserCreateManyInput[] = [];

const user: Prisma.UserCreateManyInput = {
      email: userEmail,
      password: hashedPassword,
      passwordSalt: salt,
      name: userName,
      surname: userSurname,
      balanceCents: userBalanceCents,
    };
```

**Comment by marcin98b** [comment]
> Hey, as you can see there's a bug: ![obraz](https://user-images.githubusercontent.com/33352685/201329842-0e50776a-f34c-4af2-bc50-ba58c72227d1.png)
> 
> Problem stems from the fact that during seeding we don't use sequence in postgres but insert primary keys/ids manually.
> 
> Please modify "seed.ts" script to omit primary keys. Example below:
> 
> ```ts
> // BEFORE 
> const users: User[] = [];
> 
> const user: User = {
>       userId: i,
>       email: userEmail,
>       password: hashedPassword,
>       passwordSalt: salt,
>       name: userName,
>       surname: userSurname,
>       balanceCents: userBalanceCents,
>     };
> ```
> 
> ```ts
> // AFTER: No more "userId" in object
> const users: Prisma.UserCreateManyInput[] = [];
> 
> const user: Prisma.UserCreateManyInput = {
>       email: userEmail,
>       password: hashedPassword,
>       passwordSalt: salt,
>       name: userName,
>       surname: userSurname,
>       balanceCents: userBalanceCents,
>     };
> ```

https://github.com/hyter99/AI_22-23_L1/commit/be0c6a45a0748db119a29192d1771351f7e56f84
