### ISSUE TITLE
[BE] Adjusting endpoints

### ISSUE THREAD

**Issue by Gabryjiel** [hyter99/AI_22-23_L1#42]
1. Remove "auth/logout" endpoint - it's not needed
2. Remove "/profile/:id" endpoint" - it's not needed. User data is fetched during login. Adding to that, there's no role based system, user is either logged in or not.
3. Remove "/profile/:id/transaction" - it's not needed. On client side we don't display info about user's transaction history.
4. In endpoints 'stock', '/profile/:id/stock' and 'stock/:id' returned field 'stockPriceCents' should point at minimum price of stock action in active sell offers. In endpoints "/profile/:id/stock" and "stock/:id" field "stockPriceCents" should return minimal obligation price from active sell offers.
5. In endpoint "stock/:id" field "stockPriceHistory" is list of prices from successful transactions with date.
6. In endpoint "auth/login" there should be extra field "accountBalance".
7. Add new endpoint GET "profile/:id/wallet". It should return "accountBalance" of the user.

8. In endpoints such as "profile/:id/stock", ":id" part is not needed. User can be authenticated via Bearer token.

Most propositions are by @martinZz8.

@pikrog, @BartoszGrz, any comments?

**Comment by BartoszGrz** [comment]
I would consider adding something like "/profile/me", which returns data about logged user's account.
