### ISSUE TITLE
[FE] Create stock details view

### ISSUE THREAD

**Issue by martinZz8** [hyter99/AI_22-23_L1#51]
Appearance design: https://www.figma.com/file/pHdceEatRO6lngI4f1mK7W/gie%C5%82da_projekt_v3?node-id=0%3A1 ("akcja_szczegóły" view)

Url: /szczegoly-akcji/:id (use "const {id} = useParam();" hook from ReactRouter v5 to acquire the id from url)

Note!
- Use template named "TemplateView" (with setted "isFullScreen" property) which includes menu and styling for content.
This template is now on branch "39-fe-create-view-for-all-stocks" and it's not merged with develop yet!
- Creation of buy offer modal is in another task

**Comment by Gabryjiel** [comment]
1) What do we use for data-fetching?
Should I prepare custom hook or can we use Tanstack Query (former React-Query)?

2) Can I run linter on frontend files? Every file I open it's red all over.

3) What library for charts?

**Comment by martinZz8** [comment]
Answers:
1. Actually we use **fetch** and **axios** methods.
If you would like to use other library for feetching data - feel free to use them. But I don't see it necessary since normal **fetch** function and **axios** queries are enought for this project.
2. I disabled Prietter as I just format code as I like. So maybe not for my files.
3. I haven't been thinking yet about that. Feel free to use library which you want.
