### ISSUE TITLE
[DB] Change StockPriceHistory table to CompanyStockPriceHistory

### ISSUE THREAD

**Issue by marcin98b** [hyter99/AI_22-23_L1#56]
History price of the stock should be tracked by companyId not stockId (Stock table stores actual listings of different company's stocks).
Solution: replace StockPriceHistory table with CompanyStockPriceHistory

**Comment by marcin98b** [comment]
https://github.com/hyter99/AI_22-23_L1/commit/eafbfadfcac17fd62ca5ebfe88861d9191b17f33

Task done on my side (prisma model change and seeding). Please check @Gabryjiel @BartoszGrz for further changes in back-end on old StockPriceHistory model usage and correct if any.

**Comment by marcin98b** [comment]
https://github.com/hyter99/AI_22-23_L1/tree/56-db-change-stockpricehistory-table-to-companystockpricehistory

**Comment by Gabryjiel** [comment]
Questions related in general to schema:
1) Why in "SellOffer" model there is "userStockId" but there's no relation to "UserStock" table?
2) Why in "SellOffer" there's no "stockId" but in "BuyOffer" there is?
3) What statuses are there for buyOffer and sellOffer? Could that field be enum?
4) Why is "UserStock" connected to company not user?
5) Should "Stock" even have a field called "priceCents"? I thought that users will be dictating price in sellOffers (@BartoszGrz)?
6) Why is this not a Pull Request?
7) Why stock history should be tracked by their company? If company has many stocks (do we even allow that situation?) and there's new price, stockId is better to identify stock that changed price.

**Comment by marcin98b** [comment]
> Questions related in general to schema:
> 
> 1. Why in "SellOffer" model there is "userStockId" but there's no relation to "UserStock" table?
> 2. Why in "SellOffer" there's no "stockId" but in "BuyOffer" there is?
> 3. What statuses are there for buyOffer and sellOffer? Could that field be enum?
> 4. Why is "UserStock" connected to company not user?
> 5. Should "Stock" even have a field called "priceCents"? I thought that users will be dictating price in sellOffers (@BartoszGrz)?
> 6. Why is this not a Pull Request?
> 7. Why stock history should be tracked by their company? If company has many stocks (do we even allow that situation?) and there's new price, stockId is better to identify stock that changed price.

1. Sell Offer is getting stocks owned by user in UserStock table (by userStockId).
2. Buy Offer is getting listed stock avalaible at market from Stock table (by stockId)
3. That's up to you to modify.
4. Company = Stock name issued by that company, so in other words company issues only one stock (named by company name). It's connected to user (userId) and company (companyId).
5. Buy offer can be higher/lower than listed sell offers (transaction algorithm matches these offers if buyOffer price >= sellOffer price it proceeds to create transaction).
6. Back-end needs to be adjusted for these new changes (e.g. I need new types definition to run updated seeds method https://github.com/hyter99/AI_22-23_L1/commit/be0c6a45a0748db119a29192d1771351f7e56f84 )
7. As mentioned earlier company issues only one stock (this is how it was assumed), so it's better to track in that way.

About relationship related to 1. and 2. question I can fix that in new issue but I need to be able to run updated seeds from that branch without issues for now  to merge without breaking everything (types need to be updated and also backend methods)
https://github.com/hyter99/AI_22-23_L1/issues/30#issuecomment-1311727926

Tried npx prisma generate, but these types needs to be adjusted on back-end I think (?)

Here are npx prisma migrate reset warnings
![image](https://user-images.githubusercontent.com/65306120/201358369-0629603e-c783-4682-b079-099b6608fb2d.png)
![image](https://user-images.githubusercontent.com/65306120/201358407-85309a0f-f39c-4270-aa33-7e8c5ce09dc0.png)

**Comment by Gabryjiel** [comment]
Types you chose are incorrect because of their relationships. Investigate types (you're using VS Code right?, it's "Right Click -> Go to Definition"). Types you selected for some entries are incorrent. 

Here are fixes:
- UserStockCreateInput -> UserStockUncheckedCreateInput
- StockCreateInput -> StockUncheckedCreateInput
- BuyOfferCreateInput -> BuyOfferUncheckedCreateInput
- SellOfferCreateInput -> SellOfferUncheckedCreateInput
- CompanyStockPriceHistoryCreateInput -> CompanyStockPriceHistoryUncheckedCreateInput

**Comment by Gabryjiel** [comment]
1. Ok, but there's no relationship in the model. "SellOffer" has only relationships to User and Transaction. Should be one more to UserStock.
3. So this should be enum then. Offer has three(?) states: Active, Completed(?), Expired.
4. It's relationship 1-to-1 I assume. Is there need for two tables then? Stock and Company could be one table and nothing changes.
5. So there's no need for "price" in "Stock" table then.
6. Could be a Draft PR then (when creating Pull Request there's an option for that).

**Comment by marcin98b** [comment]
> 

Yeah, I use VS. Fixed these methods, thanks.

**Comment by marcin98b** [comment]
> Types you chose are incorrect because of their relationships. Investigate types (you're using VS Code right?, it's "Right Click -> Go to Definition"). Types you selected for some entries are incorrent.
> 
> Here are fixes:
> 
> * UserStockCreateInput -> UserStockUncheckedCreateInput
> * StockCreateInput -> StockUncheckedCreateInput
> * BuyOfferCreateInput -> BuyOfferUncheckedCreateInput
> * SellOfferCreateInput -> SellOfferUncheckedCreateInput
> * CompanyStockPriceHistoryCreateInput -> CompanyStockPriceHistoryUncheckedCreateInput


Yeah, I use VS. Fixed these methods, thanks.

**Comment by marcin98b** [comment]
> Reference



> 1. Ok, but there's no relationship in the model. "SellOffer" has only relationships to User and Transaction. Should be one more to UserStock.
> 2. So this should be enum then. Offer has three(?) states: Active, Completed(?), Expired.
> 3. It's relationship 1-to-1 I assume. Is there need for two tables then? Stock and Company could be one table and nothing changes.
> 4. So there's no need for "price" in "Stock" table then.
> 5. Could be a Draft PR then (when creating Pull Request there's an option for that).

1. Yes, SellOffer and BuyOffer needs one more relationship - I'm gonna fix that.
2. Yes, something like that and maybe also "Partially completed". Can update models & seeding when It'll be agreed on.
3. For that case it needs to be like that because users will list stock offers on that Stock table (can also in batches when quantity > 1). 
4. as above
5. I'll make pull when I add that missing relationship
