### ISSUE TITLE
[DB] Prepare database schema

### ISSUE THREAD

**Issue by Gabryjiel** [hyter99/AI_22-23_L1#9]
Prepare schema:
- tables (name)
- columns (name, type)
- relations

**Comment by marcin98b** [comment]
V1 Database - PostgreSQL 14.5

![erd pgerd](https://user-images.githubusercontent.com/65306120/195664875-7e72bd8b-6a74-4968-b297-23cc58c92cb6.png)

**Comment by marcin98b** [comment]
Updated ERD - fixed naming convention and type of price
https://github.com/hyter99/AI_22-23_L1/pull/25

![erd pgerd](https://user-images.githubusercontent.com/65306120/197064001-24d63c25-431f-4ae9-8ed3-7ea1458b8b61.png)

**Comment by marcin98b** [comment]
Updated ERD - replaced StockPriceHistory with CompanyStockPriceHistory : https://github.com/hyter99/AI_22-23_L1/issues/56
![erd pgerd](https://user-images.githubusercontent.com/65306120/200960554-18a9ac1f-3055-45ef-acd6-90e88b61533a.png)

**Comment by marcin98b** [comment]
Removed stock table - transaction algorithm adjustment
![erd pgerd (2)](https://user-images.githubusercontent.com/65306120/204158485-6872954e-93e7-4b8d-9c60-466ea8d66319.png)
